"""Subclass of mainFrame, which is generated by wxFormBuilder."""

import wx
import GUI
import datetime
from models import stok

# Implementing mainFrame
class wxframe3create( GUI.Add_item ):
    def __init__( self ):
        GUI.Add_item.__init__(self, parent=None)
        self.stockModel = stok.stock()
        self.id_barang = None

    def setId(self, id_barang):
        self.id_barang = id_barang

    def setNamaBarang(self, nama_barang):
        self.namaBarang.SetValue(nama_barang)

    def setJenisBarang(self, jenis_barang):
        self.jenisBarang.SetValue(jenis_barang)

    def setHarga(self, harga_barang):
        pass

    def setJumlahBarang(self, jumlah_barang):
        self.jumlahBarang.SetValue(jumlah_barang)


        #print(birthdate, type(birthdate))
        #if (isinstance(birthdate, str)):
         #   birthdate = datetime.datetime.strptime(birthdate, '%Y-%m-%d')

        #print(birthdate, type(birthdate))
        #self.datePickerBirthDate.SetValue(birthdate)

    def saveItemClick(self, event):
        nama_barang = self.namaBarang.GetValue().strip()
        jenis_barang = self.jenisBarang.GetValue().strip()
        harga_barang = self.hargaBarang.GetValue()
        jumlah_barang = self.jumlahBarang.GetValue()

        try:
            if self.id_barang == None:
                result = self.stockModel.insert(values=[nama_barang, jenis_barang, harga_barang, jumlah_barang], columns=['nama_barang', 'jenis_barang', 'harga_barang', 'jumlah_barang'])
            else:
                result = self.stockModel.update(colValues={'nama_barang': nama_barang, 'jenis_barang': jenis_barang, 'harga_barang': harga_barang, 'jumlah_barang': jumlah_barang}, identifierValue=self.id_barang)

        except Exception as err:
            wx.MessageDialog(None, str(err), 'An error occured.', style=wx.OK | wx.ICON_ERROR).ShowModal()

        finally:
            if self.id_barang == None:
                wx.MessageDialog(None, 'New Stock successfully added.', 'Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()
            else:
                wx.MessageDialog(None, 'Stock data has been updated.', 'Update Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()