"""Subclass of mainFrame, which is generated by wxFormBuilder."""

import wx
import GUI
import datetime
from models import pegawai

# Implementing mainFrame
class wxframe4create( GUI.Add_employee ):
    def __init__( self ):
        GUI.Add_employee.__init__(self, parent=None)
        self.employeeModel = pegawai.Employee()
        self.id_pegawai = None

    def setId(self, id_pegawai):
        self.id_pegawai = id_pegawai

    def setNamaPegawai(self, nama_pegawai):
        self.namaPegawai.SetValue(nama_pegawai)

    def setAlamatPegawai(self, alamat_pegawai):
        self.alamatPegawai.SetValue(alamat_pegawai)

    def setTelpPegawai(self, telp_pegawai):
        pass

    def setUsername(self, username):
        self.usernameEmp.SetValue(username)

    def setPassword(self, password):
        self.passwordEmp.SetValue(password)

    def saveEmpClick(self, event):
        nama_pegawai = self.namaPegawai.GetValue().strip()
        alamat_pegawai = self.alamatPegawai.GetValue().strip()
        telp_pegawai = self.telpPegawai.GetValue()
        username = self.usernameEmp.GetValue()
        password = self.passwordEmp.GetValue()

        try:
            if self.id_pegawai == None:
                result = self.employeeModel.insert(values=[nama_pegawai, alamat_pegawai, telp_pegawai, username, password], columns=['nama_pegawai', 'alamat_pegawai', 'telp_pegawai', 'username', 'password'])
            else:
                result = self.employeeModel.update(colValues={'nama_pegawai': nama_pegawai, 'alamat_pegawai': alamat_pegawai, 'telp_pegawai': telp_pegawai, 'username': username, 'password': password}, identifierValue=self.id_pegawai)

        except Exception as err:
            wx.MessageDialog(None, str(err), 'An error occured.', style=wx.OK | wx.ICON_ERROR).ShowModal()

        finally:
            if self.id_pegawai == None:
                wx.MessageDialog(None, 'New User successfully added.', 'Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()
            else:
                wx.MessageDialog(None, 'User data has been updated.', 'Update Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()