"""Subclass of mainFrame, which is generated by wxFormBuilder."""

import wx
import GUI
import datetime
from models import transaksi


# Implementing mainFrame
class wxframe2create( GUI.Input_data ):
    def __init__( self ):
        GUI.Input_data.__init__(self, parent=None)
        self.transactionModel = transaksi.transaction()
        self.id_transaksi = None

    def setId(self, id_transaksi):
        self.inputIdBarangBtn = id_transaksi

    def JumlahBeli(self, jumlah_beli):
        self.inputJumlahBarangBtn = jumlah_beli

    def saveInputClick(self, event):
        id_transaksi = self.inputIdBarangBtn.GetValue()
        jumlah_beli = self.inputJumlahBarangBtn.GetValue()

        try:
            if self.id_transaksi == None:
                result = self.transactionModel.insert(values=[id_transaksi, jumlah_beli], columns=['id_transaksi', 'jumlah_beli'])
            else:
                result = self.transactionModel.update(colValues={'id_transaksi': id_transaksi, 'jumlah_beli': jumlah_beli}, identifierValue=self.id_transaksi)

        except Exception as err:
            wx.MessageDialog(None, str(err), 'An error occured.', style=wx.OK | wx.ICON_ERROR).ShowModal()

        finally:
            if self.id_transaksi == None:
                wx.MessageDialog(None, 'New Data successfully added.', 'Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()
            else:
                wx.MessageDialog(None, 'Data has been updated.', 'Update Success', style=wx.OK | wx.ICON_INFORMATION).ShowModal()